# Changes here will be overwritten by Copier
_commit: v0.3.3-18-gdb90114
_src_path: ./python-project-template/
email: e.dorta@tudelft.nl
environment_manager: pixi
full_name: A name
host: github.com
license: GPL
min_python_version: '3.12'
org: Era-Dorta
project_name: python-template-pixi-example
project_short_description: A python template pixi example.
python_name: python_template_pixi_example
url: https://github.com/Era-Dorta/python-template-pixi-example
