name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.30.0

      - name: Install the project and its dependencies
        run: pixi install -e dev

      - name: Build and deploy with mkdocs
        run: pixi run -e dev mkdocs gh-deploy --force
