name: Test Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  pytest_commit:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.30.0

      - name: Install the project and its dependencies
        run: pixi install -e dev

      - name: Run pre-commit
        run: pixi run -e dev pre-commit run --all

      - name: Run Pytest
        run: pixi run -e dev pytest --cov=src --cov-report term ./tests
